### ISSUE TITLE
For command line building consider Click.

### ISSUE THREAD

**Issue by gamefiend** [adampush/pypwman#1]
Hey there!  

I was scanning over the code and saw that you were using pyparsing to put together the commands that you will use.  That can definitely work, but I wanted to at least let you know about [Click](http://click.pocoo.org/5/), which was literally built for the what you want to do here, I think.  

My assumption is that you want to do things like:

pypwm add password 
pypwm list password
pypwm delete password

If so, definitely check out Click. It will make it easier to do what you want to do.  If I am misinterpreting it somehow, whoops! Apologies and go forward.

**Comment by adampush** [comment]
Hey, thanks for the suggestion! I have been mulling it over and I think I will try to use Click in combination with [blessed](https://github.com/jquast/blessed) and [terminaltables](https://github.com/Robpol86/terminaltables). I think with this approach I will be able to have some commands which will enter an interactive prompt state, for example to display a listing of accounts that can be navigated using the arrow keys.
